name: Update README with Images

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    update-readme:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: clone repo
              uses: actions/checkout@v3

            - name: adding screenshots
              run: |
                  echo "## Screenshots" > README.md
                  for img in docs/images*; do
                    echo "![]($img)" >> README.md
                  done

            - name: commit changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "auto update readme whit screenshots"
