name: Update README with Images

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    update-readme:
        runs-on: ubuntu-latest
        permissions:
            contents: write  # Berechtigungen für GitHub Actions setzen
        steps:
            - name: Clone repo
              uses: actions/checkout@v3

            - name: Append screenshots to README
              run: |
                  echo "## Screenshots" >> README.md
                  for img in docs/images/*; do
                    echo "<img src=\"$img\" width=\"450px\"/>" >> README.md
                  done

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "auto update readme with screenshots"
